import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";

import payrollService from "../../services/payrollService";

import "./Payroll.css";

const PayrollDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [payroll, setPayroll] = useState(null);
  const [loading, setLoading] = useState(true);

  // =====================================
  // Load Payroll Details
  // =====================================

  useEffect(() => {
    loadPayroll();
  }, []);

  const loadPayroll = async () => {
    try {
      const res = await payrollService.getPayroll(id);

      setPayroll(res.payroll);
    } catch (error) {
      toast.error("Failed to load payroll details");

      navigate("/owner/payroll");
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="loading">
        Loading Payroll Details...
      </div>
    );
  }

  if (!payroll) {
    return (
      <div className="loading">
        Payroll Not Found
      </div>
    );
  }

  return (
    <div className="payroll-details-page">

      <div className="details-card">

        <div className="details-header">

          <h2>Payroll Details</h2>

          <button
            className="back-btn"
            onClick={() => navigate("/owner/payroll")}
          >
            Back
          </button>

        </div> 

                {/* Employee Information */}

        <div className="details-section">

          <h3>Employee Information</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Employee ID</label>
              <p>{payroll.employee?.employeeId}</p>
            </div>

            <div className="detail-item">
              <label>Employee Name</label>
              <p>{payroll.employee?.name}</p>
            </div>

            <div className="detail-item">
              <label>Department</label>
              <p>{payroll.employee?.department}</p>
            </div>

            <div className="detail-item">
              <label>Designation</label>
              <p>{payroll.employee?.designation}</p>
            </div>

          </div>

        </div>

        {/* Payroll Information */}

        <div className="details-section">

          <h3>Payroll Information</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Month</label>
              <p>{payroll.month}</p>
            </div>

            <div className="detail-item">
              <label>Year</label>
              <p>{payroll.year}</p>
            </div>

            <div className="detail-item">
              <label>Payment Status</label>

              <span
                className={
                  payroll.paymentStatus === "Paid"
                    ? "status-paid"
                    : "status-pending"
                }
              >
                {payroll.paymentStatus}
              </span>

            </div>

            <div className="detail-item">
              <label>Generated By</label>
              <p>{payroll.createdBy?.name}</p>
            </div>

            <div className="detail-item">
              <label>Generated Date</label>

              <p>
                {new Date(
                  payroll.createdAt
                ).toLocaleDateString()}
              </p>

            </div>

          </div>

        </div>

        {/* Salary Details */}

        <div className="details-section">

          <h3>Salary Details</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Basic Salary</label>
              <p>₹ {payroll.basicSalary}</p>
            </div>

            <div className="detail-item">
              <label>HRA</label>
              <p>₹ {payroll.hra}</p>
            </div>

            <div className="detail-item">
              <label>Allowance</label>
              <p>₹ {payroll.allowance}</p>
            </div>

            <div className="detail-item">
              <label>Overtime</label>
              <p>₹ {payroll.overtime}</p>
            </div>

            <div className="detail-item">
              <label>Bonus</label>
              <p>₹ {payroll.bonus}</p>
            </div>

          </div>

        </div>

                {/* Deductions */}

        <div className="details-section">

          <h3>Deductions</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Provident Fund (PF)</label>
              <p>₹ {payroll.pf}</p>
            </div>

            <div className="detail-item">
              <label>ESI</label>
              <p>₹ {payroll.esi}</p>
            </div>

            <div className="detail-item">
              <label>Professional Tax</label>
              <p>₹ {payroll.professionalTax}</p>
            </div>

          </div>

        </div>

        {/* Payroll Summary */}

        <div className="details-section">

          <h3>Payroll Summary</h3>

          <div className="salary-summary">

            <div className="summary-card earnings">

              <h4>Total Earnings</h4>

              <h2>
                ₹ {payroll.totalEarnings}
              </h2>

            </div>

            <div className="summary-card deductions">

              <h4>Total Deductions</h4>

              <h2>
                ₹ {payroll.totalDeductions}
              </h2>

            </div>

            <div className="summary-card net">

              <h4>Net Salary</h4>

              <h2>
                ₹ {payroll.netSalary}
              </h2>

            </div>

          </div>

        </div>

        {/* Payment Information */}

        <div className="details-section">

          <h3>Payment Information</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Payment Status</label>

              <span
                className={
                  payroll.paymentStatus === "Paid"
                    ? "status-paid"
                    : "status-pending"
                }
              >
                {payroll.paymentStatus}
              </span>

            </div>

            <div className="detail-item">
              <label>Created By</label>

              <p>
                {payroll.createdBy?.name || "-"}
              </p>

            </div>

            <div className="detail-item">
              <label>Created On</label>

              <p>
                {new Date(
                  payroll.createdAt
                ).toLocaleString()}
              </p>

            </div>

            <div className="detail-item">
              <label>Last Updated</label>

              <p>
                {new Date(
                  payroll.updatedAt
                ).toLocaleString()}
              </p>

            </div>

          </div>

        </div>

                {/* Action Buttons */}

        <div className="details-actions">

          <button
            className="back-btn"
            onClick={() => navigate("/owner/payroll")}
          >
            Back
          </button>

          <button
            className="edit-btn"
            onClick={() =>
              navigate(`/owner/payroll/edit/${payroll._id}`)
            }
          >
            Edit Payroll
          </button>

          {payroll.paymentStatus === "Pending" && (
            <button
              className="paid-btn"
              onClick={async () => {
                try {
                  await payrollService.markAsPaid(payroll._id);

                  toast.success("Salary Marked as Paid");

                  loadPayroll();

                } catch (error) {

                  toast.error(
                    error.response?.data?.message ||
                    "Failed to update payment status"
                  );

                }
              }}
            >
              Mark as Paid
            </button>
          )}

        </div>

      </div>

    </div>
  );
};

export default PayrollDetails;