import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";

import { useAuth } from "../../context/AuthContext";

import payrollService from "../../services/payrollService";

import "./Payroll.css";

const Payslip = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const { user } = useAuth();
  const role = user?.role?.toLowerCase();

  const [payroll, setPayroll] = useState(null);
  const [loading, setLoading] = useState(true);

  // ======================================
  // Load Payroll
  // ======================================

  useEffect(() => {
    loadPayroll();
  }, []);

  const loadPayroll = async () => {
    try {
      const res = await payrollService.getPayroll(id);

      setPayroll(res.payroll);

    } catch (error) {

      toast.error("Failed to load payslip");

      navigate(`/${role}/payroll`);

    } finally {

      setLoading(false);

    }
  };

  // ======================================
  // Print Payslip
  // ======================================

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="loading">
        Loading Payslip...
      </div>
    );
  }

  if (!payroll) {
    return (
      <div className="loading">
        Payslip Not Found
      </div>
    );
  }

  return (
    <div className="payslip-page">

      <div className="payslip-card">

        {/* Header */}

        <div className="payslip-header">

          <div>

            <h1>KV Projects ERP</h1>

            <p>
              Payroll & Employee Management System
            </p>

            <p>
              Tirunelveli, Tamil Nadu
            </p>

          </div>

          <div className="company-logo">

            <h2>PAYSLIP</h2>

            <h4>
              {payroll.month} - {payroll.year}
            </h4>

          </div>

        </div>

        <hr />

                {/* ======================================
            Employee Information
        ======================================= */}

        <div className="payslip-section">

          <h3>Employee Information</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Employee ID</label>
              <p>{payroll.employee?.employeeId}</p>
            </div>

            <div className="detail-item">
              <label>Employee Name</label>
              <p>{payroll.employee?.name}</p>
            </div>

            <div className="detail-item">
              <label>Department</label>
              <p>{payroll.employee?.department}</p>
            </div>

            <div className="detail-item">
              <label>Designation</label>
              <p>{payroll.employee?.designation}</p>
            </div>

          </div>

        </div>

        {/* ======================================
            Payroll Information
        ======================================= */}

        <div className="payslip-section">

          <h3>Payroll Information</h3>

          <div className="details-grid">

            <div className="detail-item">
              <label>Month</label>
              <p>{payroll.month}</p>
            </div>

            <div className="detail-item">
              <label>Year</label>
              <p>{payroll.year}</p>
            </div>

            <div className="detail-item">
              <label>Payment Status</label>

              <span
                className={
                  payroll.paymentStatus === "Paid"
                    ? "status-paid"
                    : "status-pending"
                }
              >
                {payroll.paymentStatus}
              </span>

            </div>

            <div className="detail-item">
              <label>Generated By</label>
              <p>{payroll.createdBy?.name || "-"}</p>
            </div>

          </div>

        </div>

        {/* ======================================
            Salary Breakdown
        ======================================= */}

        <div className="payslip-section">

          <h3>Salary Breakdown</h3>

          <table className="salary-table">

            <thead>

              <tr>
                <th>Earnings</th>
                <th>Amount (₹)</th>
              </tr>

            </thead>

            <tbody>

              <tr>
                <td>Basic Salary</td>
                <td>{payroll.basicSalary}</td>
              </tr>

              <tr>
                <td>HRA</td>
                <td>{payroll.hra}</td>
              </tr>

              <tr>
                <td>Allowance</td>
                <td>{payroll.allowance}</td>
              </tr>

              <tr>
                <td>Overtime</td>
                <td>{payroll.overtime}</td>
              </tr>

              <tr>
                <td>Bonus</td>
                <td>{payroll.bonus}</td>
              </tr>

            </tbody>

          </table>

        </div>

                {/* ======================================
            Deductions
        ======================================= */}

        <div className="payslip-section">

          <h3>Deductions</h3>

          <table className="salary-table">

            <thead>
              <tr>
                <th>Deductions</th>
                <th>Amount (₹)</th>
              </tr>
            </thead>

            <tbody>

              <tr>
                <td>Provident Fund (PF)</td>
                <td>{payroll.pf}</td>
              </tr>

              <tr>
                <td>ESI</td>
                <td>{payroll.esi}</td>
              </tr>

              <tr>
                <td>Professional Tax</td>
                <td>{payroll.professionalTax}</td>
              </tr>

            </tbody>

          </table>

        </div>

        {/* ======================================
            Salary Summary
        ======================================= */}

        <div className="salary-summary">

          <div className="summary-card earnings">

            <h4>Total Earnings</h4>

            <h2>
              ₹ {payroll.totalEarnings}
            </h2>

          </div>

          <div className="summary-card deductions">

            <h4>Total Deductions</h4>

            <h2>
              ₹ {payroll.totalDeductions}
            </h2>

          </div>

          <div className="summary-card net">

            <h4>Net Salary</h4>

            <h2>
              ₹ {payroll.netSalary}
            </h2>

          </div>

        </div>

        {/* ======================================
            Amount in Words
        ======================================= */}

        <div className="payslip-section">

          <h3>Net Salary</h3>

          <div className="net-salary-box">

            <h2>
              ₹ {payroll.netSalary}
            </h2>

            <p>
              <strong>Payment Status :</strong>{" "}
              <span
                className={
                  payroll.paymentStatus === "Paid"
                    ? "status-paid"
                    : "status-pending"
                }
              >
                {payroll.paymentStatus}
              </span>
            </p>

          </div>

        </div>

        {/* ======================================
            Footer
        ======================================= */}

        <div className="payslip-footer">

          <div>
            <p><strong>Generated By:</strong></p>
            <p>{payroll.createdBy?.name || "-"}</p>
          </div>

          <div>
            <p><strong>Generated On:</strong></p>
            <p>
              {new Date(payroll.createdAt).toLocaleDateString()}
            </p>
          </div>

        </div>

                {/* ======================================
            Action Buttons
        ======================================= */}

        <div className="payslip-actions">

          <button
            className="back-btn"
            onClick={() => navigate(`/${role}/payroll`)}
          >
            Back
          </button>

          <button
            className="print-btn"
            onClick={handlePrint}
          >
            Print Payslip
          </button>

        </div>

      </div>

    </div>
  );
};

export default Payslip;